<#
.SYNOPSIS
  Pre-computes a repo digest for the planner so it doesn't have to scan the
  whole codebase each run. Output: <run-dir>/plan-context.md.

.PARAMETER PromptPath
  Path to prompt.md. The plan-context.md is written next to it.

.PARAMETER MaxSlices
  Maximum number of similar slices to list (default 10).

.PARAMETER MaxRules
  Maximum number of "Generalize as rule" entries to pull from
  docs/agent-decisions.md (default 10).

.NOTES
  Exit codes:
    0  context written
    3  invalid args / prompt not found
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$PromptPath,
    [int]$MaxSlices = 10,
    [int]$MaxRules  = 10
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path "$PSScriptRoot/..").Path

if (-not (Test-Path $PromptPath)) {
    Write-Error "[plan-context] prompt not found: $PromptPath"
    exit 3
}

$promptFull = (Resolve-Path $PromptPath).Path
$runDir = Split-Path $promptFull -Parent
$outPath = Join-Path $runDir 'plan-context.md'

# --- Tokenize prompt into keywords ----------------------------------------
$stopWords = @(
    'the','and','for','with','that','this','from','have','will','are','was',
    'but','not','you','your','our','can','should','must','need','want','add',
    'new','use','using','make','any','all','one','two','let','them','they',
    'a','an','of','to','in','on','it','is','as','by','be','or','at','if',
    'do','so','we','i','me','my','his','her','their','its','also','just',
    'than','then','now','only','some','more','most','many','few','here','there',
    'aby','oraz','dla','jest','są','być','żeby','które','który','którzy','która',
    'tak','nie','też','już','jak','co','tylko','można','należy','warto','przy',
    'tym','tej','ten','ta','to','jeśli','aby','dla','jako','nowy','nowa','nowe',
    'i','w','z','o','na','do','po','od','u','ze','we','przez','między','tak'
)
$promptText  = Get-Content $promptFull -Raw -ErrorAction SilentlyContinue
if (-not $promptText) { $promptText = '' }
$tokens = [regex]::Matches($promptText.ToLowerInvariant(), '[a-ząćęłńóśżź]{4,}') |
    ForEach-Object { $_.Value } |
    Where-Object { $stopWords -notcontains $_ }
$keywordFreq = $tokens | Group-Object | Sort-Object Count -Descending
$keywords    = $keywordFreq | Select-Object -First 12 -ExpandProperty Name
if (-not $keywords) { $keywords = @() }

# --- Find similar slices --------------------------------------------------
$featuresRoot = Join-Path $repoRoot 'src/BookSlot.Features/Features'
$similarSlices = @()
if (Test-Path $featuresRoot) {
    $allSlices = Get-ChildItem $featuresRoot -Directory | ForEach-Object {
        $area = $_.Name
        Get-ChildItem $_.FullName -Directory | ForEach-Object {
            [pscustomobject]@{
                Area   = $area
                Op     = $_.Name
                RelPath= "src/BookSlot.Features/Features/$area/$($_.Name)"
            }
        }
    }
    $scored = $allSlices | ForEach-Object {
        $hay = "$($_.Area) $($_.Op)".ToLowerInvariant()
        $score = 0
        foreach ($k in $keywords) { if ($hay -match [regex]::Escape($k)) { $score++ } }
        [pscustomobject]@{ Slice = $_; Score = $score }
    }
    $similarSlices = $scored |
        Where-Object { $_.Score -gt 0 } |
        Sort-Object Score -Descending |
        Select-Object -First $MaxSlices -ExpandProperty Slice
    if (-not $similarSlices -or $similarSlices.Count -eq 0) {
        # No keyword match: fall back to a stable sample of recent slices.
        $similarSlices = $allSlices | Select-Object -First $MaxSlices
    }
}

# --- List domain entities -------------------------------------------------
$domainRoot = Join-Path $repoRoot 'src/BookSlot.Domain'
$entities = @()
if (Test-Path $domainRoot) {
    $entities = Get-ChildItem $domainRoot -Recurse -Filter '*.cs' -File |
        Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' } |
        ForEach-Object {
            $rel = $_.FullName.Substring($repoRoot.Length).TrimStart('\','/').Replace('\','/')
            $rel
        } |
        Sort-Object
}

# --- Pull last N "Generalize as rule" entries -----------------------------
$decisionsPath = Join-Path $repoRoot 'docs/agent-decisions.md'
$rules = @()
if (Test-Path $decisionsPath) {
    $raw = Get-Content $decisionsPath -Raw
    $matches = [regex]::Matches(
        $raw,
        '(?ms)^###\s+Generalize as rule:.*?(?=^###\s|\Z)'
    )
    if ($matches.Count -gt 0) {
        $rules = @($matches | ForEach-Object { $_.Value.Trim() })
        if ($rules.Count -gt $MaxRules) {
            $rules = $rules[($rules.Count - $MaxRules)..($rules.Count - 1)]
        }
    }
}

# --- Render ---------------------------------------------------------------
$nl = [Environment]::NewLine
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# Plan context')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Auto-generated by `scripts/plan-context.ps1`. Treat as a deterministic')
[void]$sb.AppendLine('digest of the repo to anchor planning. Do **not** edit by hand.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Keywords extracted from prompt')
[void]$sb.AppendLine()
if ($keywords.Count -eq 0) {
    [void]$sb.AppendLine('_(no keywords extracted)_')
} else {
    [void]$sb.AppendLine('`' + ($keywords -join '`, `') + '`')
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Similar / candidate slices')
[void]$sb.AppendLine()
if ($similarSlices.Count -eq 0) {
    [void]$sb.AppendLine('_(no slices found — repo may be empty)_')
} else {
    [void]$sb.AppendLine('| Area | Op | Path |')
    [void]$sb.AppendLine('|------|----|------|')
    foreach ($s in $similarSlices) {
        [void]$sb.AppendLine("| $($s.Area) | $($s.Op) | ``$($s.RelPath)`` |")
    }
}
[void]$sb.AppendLine()
[void]$sb.AppendLine("## Domain entities ($($entities.Count) files)")
[void]$sb.AppendLine()
if ($entities.Count -eq 0) {
    [void]$sb.AppendLine('_(none)_')
} else {
    [void]$sb.AppendLine('<details><summary>full list</summary>')
    [void]$sb.AppendLine()
    foreach ($e in $entities) { [void]$sb.AppendLine("- ``$e``") }
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('</details>')
}
[void]$sb.AppendLine()
[void]$sb.AppendLine("## Last $MaxRules `Generalize as rule:` entries from agent-decisions.md")
[void]$sb.AppendLine()
if ($rules.Count -eq 0) {
    [void]$sb.AppendLine('_(no rules recorded yet)_')
} else {
    foreach ($r in $rules) {
        [void]$sb.AppendLine($r)
        [void]$sb.AppendLine()
    }
}

Set-Content -Path $outPath -Value $sb.ToString() -Encoding UTF8 -NoNewline
Write-Host "[plan-context] wrote: $outPath"
Write-Host "[plan-context] keywords: $($keywords.Count)  slices: $($similarSlices.Count)  entities: $($entities.Count)  rules: $($rules.Count)"
exit 0
