<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyHomeRamen.Common.Contracts\MyHomeRamen.Common.Contracts.csproj" />
		<ProjectReference Include="..\MyHomeRamen.Domain\MyHomeRamen.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Restaurants\" />
		<Folder Include="Reservations\" />
	</ItemGroup>
</Project>
