<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Reservations\Authorization\**" />
    <EmbeddedResource Remove="Reservations\Authorization\**" />
    <None Remove="Reservations\Authorization\**" />
  </ItemGroup>
 
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="ShoppingCart\Database\" />
  </ItemGroup>

</Project>
