<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyHomeRamen.Common.Contracts\MyHomeRamen.Common.Contracts.csproj" />
    <ProjectReference Include="..\MyHomeRamen.Domain\MyHomeRamen.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PaymentsModule\Users\" />
  </ItemGroup>
</Project>