// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHomeRamen.Persistance.Restaurants;

#nullable disable

namespace MyHomeRamen.Persistance.Restaurants.Migrations
{
    [DbContext(typeof(RestaurantsDbContext))]
    partial class RestaurantsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("restaurants")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Companies.CompanyDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companies", "restaurants");
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Companies.SocialMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyDetailsId");

                    b.ToTable("CompanySocialMedia", "restaurants");
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Restaurants.ClosingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantClosingPeriods", "restaurants");
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", "restaurants");
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Companies.CompanyDetails", b =>
                {
                    b.OwnsOne("MyHomeRamen.Domain.Restaurants.Companies.ValueObjects.BusinessDetails", "BusinessDetails", b1 =>
                        {
                            b1.Property<Guid>("CompanyDetailsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("LegalName");

                            b1.Property<string>("TaxId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TaxId");

                            b1.HasKey("CompanyDetailsId");

                            b1.ToTable("Companies", "restaurants");

                            b1.WithOwner()
                                .HasForeignKey("CompanyDetailsId");
                        });

                    b.Navigation("BusinessDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Companies.SocialMedia", b =>
                {
                    b.HasOne("MyHomeRamen.Domain.Restaurants.Companies.CompanyDetails", null)
                        .WithMany("Media")
                        .HasForeignKey("CompanyDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Restaurants.ClosingPeriod", b =>
                {
                    b.HasOne("MyHomeRamen.Domain.Restaurants.Restaurants.Restaurant", null)
                        .WithMany("ClosingPeriods")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Restaurants.Restaurant", b =>
                {
                    b.OwnsOne("MyHomeRamen.Domain.Restaurants.Restaurants.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants", "restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");

                            b1.OwnsOne("MyHomeRamen.Domain.Restaurants.Restaurants.ValueObjects.Location", "Location", b2 =>
                                {
                                    b2.Property<Guid>("AddressRestaurantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("AddressRestaurantId");

                                    b2.ToTable("Restaurants", "restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressRestaurantId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.OwnsOne("MyHomeRamen.Domain.Restaurants.Restaurants.ValueObjects.BankAccount", "BankAccount", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("AccountNumber");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BankName");

                            b1.Property<string>("RoutingNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("RoutingNumber");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants", "restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("MyHomeRamen.Domain.Restaurants.Restaurants.ValueObjects.ContactDetails", "ContactDetails", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("Phone");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants", "restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsMany("MyHomeRamen.Domain.Restaurants.Restaurants.ValueObjects.WorkingHours", "WorkHours", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeSpan>("CloseTime")
                                .HasColumnType("time");

                            b1.Property<DateOnly>("Day")
                                .HasColumnType("date");

                            b1.Property<TimeSpan>("OpenTime")
                                .HasColumnType("time");

                            b1.HasKey("RestaurantId", "Id");

                            b1.ToTable("RestaurantWorkingHours", "restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BankAccount")
                        .IsRequired();

                    b.Navigation("ContactDetails")
                        .IsRequired();

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Companies.CompanyDetails", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("MyHomeRamen.Domain.Restaurants.Restaurants.Restaurant", b =>
                {
                    b.Navigation("ClosingPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
