<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UserSecretsId>f529ae8b-2380-469c-b437-149c75cd3259</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyHomeRamen.Domain\MyHomeRamen.Domain.csproj" />
    <ProjectReference Include="..\MyHomeRamen.Features\MyHomeRamen.Features.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Orders\Users\" />
  </ItemGroup>

</Project>
