<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MyHomeRamen.Api.Common\MyHomeRamen.Api.Common.csproj" />
		<ProjectReference Include="..\MyHomeRamen.Api\MyHomeRamen.Api.csproj" />
		<ProjectReference Include="..\MyHomeRamen.Domain\MyHomeRamen.Domain.csproj" />
		<ProjectReference Include="..\MyHomeRamen.Persistance\MyHomeRamen.Persistance.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>
</Project>